# Exported from Render on 2024-10-11T21:47:27Z
services:
- type: web
  name: aplicacion_web
  runtime: python
  repo: https://github.com/Andrea0823/aplicacion_web.git
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: cd web && python app.py

- type: web
  name: api_rest
  runtime: python
  repo: https://github.com/Andrea0823/api_rest.git
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port 8000

databases:
- name: agenda
  databaseName: db_agenda_sd8j
  user: user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"

version: "1"
